name: .NET CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Replace with your .NET version

    - name: Install dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --configuration Release

    - name: Publish the application
      run: dotnet publish --configuration Release --output ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Replace with your .NET version

    - name: Publish the application
      run: dotnet publish --configuration Release --output PracticeWithGithubActions.API .\PracticeWithGithubActions-API

    - name: Deploy to Local IIS
      run: Copy-Item -Path ./PracticeWithGithubActions-API/* -Destination C:/inetpub/wwwroot/GithubActions -Recurse -Force

    - name: Restart IIS
      run: iisreset
      shell: cmd
