name: .NET CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'  # Replace with your .NET version

    - name: Install dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build --no-restore -c Release

    - name: Run tests
      run: dotnet test --no-build -c Release

    - name: Publish the application
      run: dotnet publish -c Release -o PracticeWithGithubActions-API

    - name: Deploy to Local IIS
      run: | 
        iisreset /stop
        Copy-Item -Path ./PracticeWithGithubActions-API/* -Destination C:/inetpub/wwwroot/GithubActions -Recurse -Force
        iisreset /start

    - name: Curl the website as a smoke test
      run: curl http://localhost/GithubActions
